packages:
  - "."
  - "example/react"
  - "example/vue"
  - "example/solid"
  - "example/svelte"
  - "providers/role-created-event-listener"

allowBuilds:
  b: true
  d: true
  e: true
  esbuild: true
  i: true
  l: true
  s: true
  u: true
